# Generated by Django 4.2.9 on 2024-02-17 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("item_id", models.CharField(max_length=100)),
                ("item_name", models.CharField(default="Item_Picture", max_length=100)),
                (
                    "item_pic",
                    models.ImageField(blank=True, null=True, upload_to="Item_Image"),
                ),
                (
                    "item_type",
                    models.CharField(
                        choices=[
                            ("PERISHABLE", "perishable"),
                            ("NON-PERISHABLE", "non_perishable"),
                        ],
                        max_length=100,
                    ),
                ),
                ("description", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Organization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("org_id", models.CharField(max_length=100)),
                ("org_name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Pricing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("zone", models.CharField(max_length=100)),
                ("base_distance_in_km", models.IntegerField(null=True)),
                ("km_price", models.FloatField()),
                ("fix_price", models.IntegerField(null=True)),
                (
                    "item",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items_id",
                        to="DlvryApp.item",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orgnize_id",
                        to="DlvryApp.organization",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="item",
            constraint=models.UniqueConstraint(
                fields=("item_id",), name="unique_item_id_no"
            ),
        ),
    ]
