# Generated by Django 4.2.9 on 2024-02-15 06:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("DlvryApp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="pricing",
            name="base_distance_in_km",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="pricing",
            name="fix_price",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="pricing",
            name="km_price",
            field=models.CharField(max_length=100),
        ),
    ]
