# Generated by Django 5.0.2 on 2024-02-22 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DlvryApp', '0002_signupmodel'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='signupmodel',
            constraint=models.UniqueConstraint(fields=('email',), name='unique_email'),
        ),
    ]
