# Generated by Django 4.2.9 on 2024-02-15 09:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("DlvryApp", "0003_alter_organization_org_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="pricing",
            old_name="item_id",
            new_name="item",
        ),
        migrations.RenameField(
            model_name="pricing",
            old_name="organization_id",
            new_name="organization",
        ),
    ]
