# Generated by Django 4.2.9 on 2024-02-15 09:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("DlvryApp", "0004_rename_item_id_pricing_item_and_more"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="item",
            constraint=models.UniqueConstraint(
                fields=("item_id",), name="unique_item_id_no"
            ),
        ),
    ]
