# Generated by Django 4.2.9 on 2024-02-15 09:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("DlvryApp", "0005_item_unique_item_id_no"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pricing",
            name="km_price",
            field=models.IntegerField(max_length=100),
        ),
    ]
