# Generated by Django 4.2.9 on 2024-02-15 09:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("DlvryApp", "0006_alter_pricing_km_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pricing",
            name="km_price",
            field=models.FloatField(),
        ),
    ]
